![](https://miro.medium.com/max/412/1*Y-tB8ue9D1B7ZImpjYGXUA.png)

In [38]:
import pandas as pd

In [25]:
data=pd.read_csv('marks_data.csv')

In [26]:
type(data)

pandas.core.frame.DataFrame

In [27]:
# DEPENDENT VARIABLE
y=data["marks"]

print(y)

0     70
1     50
2     60
3     80
4    100
Name: marks, dtype: int64


In [32]:
# INDEPENDENT VARIABLE
x=data["hrs"]

#############doubt##############
x=x.values   # converts pandas to numpy
x=x.reshape(-1,1)
###############################
print(x)

[[ 7]
 [ 5]
 [ 6]
 [ 8]
 [10]]


In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
mind=LinearRegression()

In [33]:
mind.fit(x,y)

LinearRegression()

In [34]:
mind.predict([[2]])

array([20.])

In [35]:
mind.coef_

array([10.])

In [36]:
import joblib

In [37]:
joblib.dump(mind , "marks.pk1")

['marks.pk1']